# Generated by Django 3.2.23 on 2024-03-06 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='images/profiles/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sn_facebook', models.CharField(blank=True, max_length=255)),
                ('sn_twitter', models.CharField(blank=True, max_length=255)),
                ('sn_linkedin', models.CharField(blank=True, max_length=255)),
                ('sn_instagram', models.CharField(blank=True, max_length=255)),
                ('sn_github', models.CharField(blank=True, max_length=255)),
                ('sn_youtube', models.CharField(blank=True, max_length=255)),
                ('sn_website', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
