# Generated by Django 3.2.23 on 2024-03-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240306_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='localtion',
            new_name='location',
        ),
    ]
