# Generated by Django 3.2.23 on 2024-03-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
